[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "public"
  publish = "public"
  command = "/opt/buildhome/.nvm/versions/node/v14.17.6/bin/npm run build"


[dev]
  command = "npm start"
